# Generated by Django 5.0.2 on 2024-03-31 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20220225_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedcustomerappointment',
            name='engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EngineerApprovedApp', to='appointments.engineer'),
        ),
    ]
