# Generated by Django 5.0.2 on 2024-04-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_approvedcustomerappointment_engineer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='service_field',
            field=models.CharField(choices=[('Маникюр', 'Маникюр'), ('Педикюр', 'Педикюр'), ('Ресницы', 'Ресницы')], default='Service and Repair', max_length=50),
        ),
    ]
